apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backendsvc
  name: backendsvc
  namespace: praba
spec:
  ports:
  - name: 8085-8080
    port: 8085
    protocol: TCP
    targetPort: 8080
  selector:
    app: backendsvc
  type: LoadBalancer
status:
  loadBalancer: {}
