apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontendsvc
  name: frontendsvc
  namespace: praba
spec:
  ports:
  - name: 8084-8080
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontendsvc
  type: LoadBalancer
status:
  loadBalancer: {}
